### ISSUE TITLE
Beginning - Setup Environment, Submit a working Bot

### ISSUE THREAD

**Issue by OrsoEric** [OrsoEric/kaggle-Lux-AI#3]
- [x] Set up the environmet to run the challenge locally @OrsoEric 
- [x] Write a simple bot that do random actions @OrsoEric 
- [x] Set up the environmet to run the challenge locally @dgcrox 
- [x] Set up the environmet to run the challenge locally @jayfranck 

Python Version: Conda 3.7
- [x] #9

**Comment by OrsoEric** [comment]
WINDOWS:
0) [Instructions](https://github.com/Lux-AI-Challenge/Lux-Design-2021#getting-started)
1a) Download and install [Python 3.7](https://www.python.org/downloads/release/python-370/)
1b) Check python is working on CMD by executing "python" "exit()" and "pip"
2a) Download and Install [NODE.JS](https://nodejs.org/en/download/)
2b) Check node is working on CMD by executing "node -v" "npm"
3a) Install LUX-AI node package on CMD by executing "npm install -g @lux-ai/2021-challenge@latest"
3b) Check challenge engine by executing on CMD "lux-ai-2021 --help"
4a) Download working python bot from our team "La Compagnia del Carretto" [Released Bot](https://github.com/OrsoEric/kaggle-Lux-AI/tree/submissions)
4b) with CMD "cd" into the folder with main.py
4c) execute game engine on our released bot "lux-ai-2021 main.py main.py --out=replay.json"

VSCODE IDE
1) Install Git, Install VSCode, install "Python" extensions, install "Git Graph" extensions and make sure python works
2) clone our team repository, select the submission branch
3) play main.py, the bot will do nothing because it waits input() terminate with ctrl+c
4) on the same VSCode terminal execute "lux-ai-2021 main.py main.py --out=replay.json"
![image](https://user-images.githubusercontent.com/30684972/134629893-43cc53da-3c66-4a55-be5e-83799272f67f.png)
